### ISSUE TITLE
ability to only select tags that include value

### ISSUE THREAD

**Issue by ramonskie** [bonclay7/aws-amicleaner#116]
when having images with
```
tag:
 - foo: bar
 - name: test
 - published: false
```
```
tag:
 - foo: bar
 - name: test_test
 - published: false
 ```
 
 i want to be able to select only the ami's with `name:test` and `published:false`
as i cannot be sure of if there are amis with the tag `name:example`
i cannot mis/abuse the `--excluded-mapping-values test_test`  for example.

is there an ability to just say i want only to remove the one containing 2 tags and there corosponding values.
like `--include-mapping-values name=test, published:false`
